// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djvmglptyuhamwqmbbhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdm1nbHB0eXVoYW13cW1iYmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMTEzNjAsImV4cCI6MjA3NDU4NzM2MH0.6whNC8mxTUdeNVu-WKau1SiBlNmHMIWvL9tSzXidORM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});